# Generated by Django 5.2.1 on 2025-07-17 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogmodel',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
