# Generated by Django 5.2.1 on 2025-07-17 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0003_profile_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogmodel',
            options={'verbose_name': 'Blog Entries', 'verbose_name_plural': 'Blog Entries'},
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
