# Generated by Django 5.2.1 on 2025-05-26 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('company', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20)),
                ('message', models.TextField()),
                ('website_development', models.BooleanField(default=False)),
                ('app_development', models.BooleanField(default=False)),
                ('marketing', models.BooleanField(default=False)),
                ('other', models.BooleanField(default=False)),
                ('other_description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Contact Form Entry',
                'verbose_name_plural': 'Contact Form Entries',
            },
        ),
        migrations.CreateModel(
            name='CustomerStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('happy_clients', models.PositiveIntegerField(default=0)),
                ('projects_completed', models.PositiveIntegerField(default=0)),
                ('full_time_specialists', models.PositiveIntegerField(default=0)),
                ('awards_won', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='NewsletterSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('subscribed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Newsletter Subscription',
                'verbose_name_plural': 'Newsletter Subscription',
            },
        ),
        migrations.CreateModel(
            name='PhoneCall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=15, verbose_name='Phone Number')),
                ('scheduled_at', models.DateTimeField(auto_now_add=True, verbose_name='Scheduled At')),
            ],
            options={
                'verbose_name': 'Scheduled call',
                'verbose_name_plural': 'Scheduled call',
            },
        ),
    ]
