# Generated by Django 5.2.1 on 2025-07-17 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0002_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='designation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='experience_1',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Experience 1'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='experience_1_desc',
            field=models.TextField(blank=True, null=True, verbose_name='Experience 1 Description'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='experience_2',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Experience 2'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='experience_2_desc',
            field=models.TextField(blank=True, null=True, verbose_name='Experience 2 Description'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='experience_3',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Experience 3'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='experience_3_desc',
            field=models.TextField(blank=True, null=True, verbose_name='Experience 3 Description'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='experience_4',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Experience 4'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='experience_4_desc',
            field=models.TextField(blank=True, null=True, verbose_name='Experience 4 Description'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='github',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='instagram',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='linkedin',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='portfolio_link',
            field=models.URLField(blank=True, null=True, verbose_name='Portfolio Link'),
        ),
    ]
