# Generated by Django 5.2.1 on 2025-07-17 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0003_userprofile_address_userprofile_designation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='address',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='designation',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='experience_1',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='experience_1_desc',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='experience_2',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='experience_2_desc',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='experience_3',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='experience_3_desc',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='experience_4',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='experience_4_desc',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='github',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='instagram',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='linkedin',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='phone',
        ),
    ]
